export type Player = {
  firstName: string;
  lastName: string;
  team: string;
  position: "F" | "G" | "C";
  role: "starter" | "reserve" | "captain";
  pick: number;
}

export const players: Player[] = [
  {
    firstName: "LeBron",
    lastName: "James",
    team: "LAL",
    position: "F",
    role: "captain",
    pick: 0,
  },
  {
    firstName: "Nikola",
    lastName: "Jokić",
    team: "DEN",
    position: "F",
    role: "starter",
    pick: 21,
  },
  {
    firstName: "Joel",
    lastName: "Embiid",
    team: "PHI",
    position: "C",
    role: "starter",
    pick: 15,
  },
  {
    firstName: "Kyrie",
    lastName: "Irving",
    team: "DAL",
    position: "G",
    role: "starter",
    pick: 17,
  },
  {
    firstName: "Luka",
    lastName: "Dončić",
    team: "DAL",
    position: "G",
    role: "starter",
    pick: 19,
  },
  {
    firstName: "Anthony",
    lastName: "Edwards",
    team: "MIN",
    position: "F",
    role: "reserve",
    pick: 2,
  },
  {
    firstName: "Jaylen",
    lastName: "Brown",
    team: "BOS",
    position: "G",
    role: "reserve",
    pick: 4,
  },
  {
    firstName: "Paul",
    lastName: "George",
    team: "LAC",
    position: "F",
    role: "reserve",
    pick: 6,
  },
  {
    firstName: "Tyrese",
    lastName: "Haliburton",
    team: "IND",
    position: "G",
    role: "reserve",
    pick: 8,
  },
  {
    firstName: "Julius",
    lastName: "Randle",
    team: "NYK",
    position: "F",
    role: "reserve",
    pick: 10,
  },
  {
    firstName: "De'Aaron",
    lastName: "Fox",
    team: "SAC",
    position: "G",
    role: "reserve",
    pick: 12,
  },
  {
    firstName: "Jaren",
    lastName: "Jackson Jr.",
    team: "MEM",
    position: "F",
    role: "reserve",
    pick: 14,
  },
  {
    firstName: "Giannis",
    lastName: "Antetokounmpo",
    team: "MIL",
    position: "F",
    role: "captain",
    pick: 0,
  },
  {
    firstName: "Lauri",
    lastName: "Markkanen",
    team: "UTA",
    position: "F",
    role: "starter",
    pick: 22,
  },
  {
    firstName: "Donovan",
    lastName: "Mitchell",
    team: "CLE",
    position: "G",
    role: "starter",
    pick: 20,
  },
  {
    firstName: "Ja",
    lastName: "Morant",
    team: "MEM",
    position: "G",
    role: "starter",
    pick: 18,
  },
  {
    firstName: "Jayson",
    lastName: "Tatum",
    team: "BOS",
    position: "G",
    role: "starter",
    pick: 16,
  },
  {
    firstName: "Damiam",
    lastName: "Lillard",
    team: "POR",
    position: "G",
    role: "reserve",
    pick: 1,
  },
  {
    firstName: "Jrue",
    lastName: "Holiday",
    team: "MIL",
    position: "G",
    role: "reserve",
    pick: 3,
  },
  {
    firstName: "Shai",
    lastName: "Gilgeous-Alexander",
    team: "OKC",
    position: "G",
    role: "reserve",
    pick: 5,
  },
  {
    firstName: "DeMar",
    lastName: "DeRozan",
    team: "CHI",
    position: "G",
    role: "reserve",
    pick: 7,
  },
  {
    firstName: "Pascal",
    lastName: "Siakam",
    team: "TOR",
    position: "G",
    role: "reserve",
    pick: 9,
  },
  {
    firstName: "Bam",
    lastName: "Adebayo",
    team: "MIA",
    position: "C",
    role: "reserve",
    pick: 11,
  },
  {
    firstName: "Domantas",
    lastName: "Sabonis",
    team: "SAC",
    position: "C",
    role: "reserve",
    pick: 13,
  },
]
