export type Player = {
  firstName: string;
  lastName: string;
  team: string;
  position: "F" | "G" | "C";
  role: "starter" | "reserve" | "captain";
  pick: number;
  espnId: number;
}

export const players: Player[] = [
  {
    firstName: "LeBron",
    lastName: "James",
    team: "LAL",
    position: "F",
    role: "captain",
    pick: 0,
    espnId: 1966,
  },
  {
    firstName: "Nikola",
    lastName: "Jokić",
    team: "DEN",
    position: "F",
    role: "starter",
    pick: 21,
    espnId: 3112335,
  },
  {
    firstName: "Joel",
    lastName: "Embiid",
    team: "PHI",
    position: "C",
    role: "starter",
    pick: 15,
    espnId: 3059318,
  },
  {
    firstName: "Kyrie",
    lastName: "Irving",
    team: "DAL",
    position: "G",
    role: "starter",
    pick: 17,
    espnId: 6442,
  },
  {
    firstName: "Luka",
    lastName: "Dončić",
    team: "DAL",
    position: "G",
    role: "starter",
    pick: 19,
    espnId: 3945274,
  },
  {
    firstName: "Anthony",
    lastName: "Edwards",
    team: "MIN",
    position: "F",
    role: "reserve",
    pick: 2,
    espnId: 4594268,
  },
  {
    firstName: "Jaylen",
    lastName: "Brown",
    team: "BOS",
    position: "G",
    role: "reserve",
    pick: 4,
    espnId: 3917376,
  },
  {
    firstName: "Paul",
    lastName: "George",
    team: "LAC",
    position: "F",
    role: "reserve",
    pick: 6,
    espnId: 4251,
  },
  {
    firstName: "Tyrese",
    lastName: "Haliburton",
    team: "IND",
    position: "G",
    role: "reserve",
    pick: 8,
    espnId: 4396993,
  },
  {
    firstName: "Julius",
    lastName: "Randle",
    team: "NYK",
    position: "F",
    role: "reserve",
    pick: 10,
    espnId: 3064514,
  },
  {
    firstName: "De'Aaron",
    lastName: "Fox",
    team: "SAC",
    position: "G",
    role: "reserve",
    pick: 12,
    espnId: 4066259,
  },
  {
    firstName: "Jaren",
    lastName: "Jackson Jr.",
    team: "MEM",
    position: "F",
    role: "reserve",
    pick: 14,
    espnId: 4277961,
  },
  {
    firstName: "Giannis",
    lastName: "Antetokounmpo",
    team: "MIL",
    position: "F",
    role: "captain",
    pick: 0,
    espnId: 3032977,
  },
  {
    firstName: "Lauri",
    lastName: "Markkanen",
    team: "UTA",
    position: "F",
    role: "starter",
    pick: 22,
    espnId: 4066336,
  },
  {
    firstName: "Donovan",
    lastName: "Mitchell",
    team: "CLE",
    position: "G",
    role: "starter",
    pick: 20,
    espnId: 3908809,
  },
  {
    firstName: "Ja",
    lastName: "Morant",
    team: "MEM",
    position: "G",
    role: "starter",
    pick: 18,
    espnId: 4279888,
  },
  {
    firstName: "Jayson",
    lastName: "Tatum",
    team: "BOS",
    position: "G",
    role: "starter",
    pick: 16,
    espnId: 4065648,
  },
  {
    firstName: "Damiam",
    lastName: "Lillard",
    team: "POR",
    position: "G",
    role: "reserve",
    pick: 1,
    espnId: 6606,
  },
  {
    firstName: "Jrue",
    lastName: "Holiday",
    team: "MIL",
    position: "G",
    role: "reserve",
    pick: 3,
    espnId: 3995,
  },
  {
    firstName: "Shai",
    lastName: "Gilgeous-Alexander",
    team: "OKC",
    position: "G",
    role: "reserve",
    pick: 5,
    espnId: 4278073,
  },
  {
    firstName: "DeMar",
    lastName: "DeRozan",
    team: "CHI",
    position: "G",
    role: "reserve",
    pick: 7,
    espnId: 3978,
  },
  {
    firstName: "Pascal",
    lastName: "Siakam",
    team: "TOR",
    position: "G",
    role: "reserve",
    pick: 9,
    espnId: 3149673,
  },
  {
    firstName: "Bam",
    lastName: "Adebayo",
    team: "MIA",
    position: "C",
    role: "reserve",
    pick: 11,
    espnId: 4066261,
  },
  {
    firstName: "Domantas",
    lastName: "Sabonis",
    team: "SAC",
    position: "C",
    role: "reserve",
    pick: 13,
    espnId: 3155942,
  },
]
